sudo: required
services:
  - docker

before_install:
  - docker build -t conaryh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true conaryh/react-test npm test

after_success:
  - docker build -t conaryh/multi-client ./client
  - docker build -t conaryh/multi-nginx ./nginx
  - docker build -t conaryh/multi-server ./server
  - docker build -t conaryh/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push conaryh/multi-client
  - docker push conaryh/multi-nginx
  - docker push conaryh/multi-server
  - docker push conaryh/multi-worker
